# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Proyectos\Proyectos_Python\Odontologia\Interfaces\guiAcceso.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import ctypes


class Ui_frmAcceso(object):
    def setupUi(self, frmAcceso):
        #Obtenemos el ancho y alto de la pantalla
        user32 = ctypes.windll.user32
        ancho_pantalla = user32.GetSystemMetrics(0)
        alto_pantalla = user32.GetSystemMetrics(1)
        #
        frmAcceso.setObjectName("frmAcceso")
        frmAcceso.resize(int(ancho_pantalla * 970 / 1920), int(alto_pantalla * 373 / 1080))
        valor = int(ancho_pantalla * 50 / 1920)
        frmAcceso.setStyleSheet(f"background-color: rgb(40, 0, 70); border-radius: {valor}px; ")
        self.centralwidget = QtWidgets.QWidget(frmAcceso)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(int(ancho_pantalla * 130 / 1920), int(alto_pantalla * 50 / 1080), int(ancho_pantalla * 260 / 1920), int(alto_pantalla * 40 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 22 / 1920))
        self.label.setFont(font)
        self.label.setStyleSheet("color: white;")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(int(ancho_pantalla * 30 / 1920), int(alto_pantalla * 40 / 1080), int(ancho_pantalla * 70 / 1920), int(alto_pantalla * 70 / 1080)))
        self.pushButton.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Imagenes/Usuario.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(int(ancho_pantalla * 70 / 1920), int(alto_pantalla * 70 / 1080)))
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(int(ancho_pantalla * 50 / 1920), int(alto_pantalla * 190 / 1080), int(ancho_pantalla * 80 / 1920), int(alto_pantalla * 20 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: white;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(int(ancho_pantalla * 50 / 1920), int(alto_pantalla * 250 / 1080), int(ancho_pantalla * 110 / 1920), int(alto_pantalla * 20 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: white;")
        self.label_3.setObjectName("label_3")
        self.txtUsuario = QtWidgets.QLineEdit(self.centralwidget)
        self.txtUsuario.setGeometry(QtCore.QRect(int(ancho_pantalla * 170 / 1920), int(alto_pantalla * 190 / 1080), int(ancho_pantalla * 460 / 1920), int(alto_pantalla * 30 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.txtUsuario.setFont(font)
        self.txtUsuario.setStyleSheet("background-color: white;")
        self.txtUsuario.setText("")
        self.txtUsuario.setObjectName("txtUsuario")
        self.txtContrasenia = QtWidgets.QLineEdit(self.centralwidget)
        self.txtContrasenia.setGeometry(QtCore.QRect(int(ancho_pantalla * 170 / 1920), int(alto_pantalla * 250 / 1080), int(ancho_pantalla * 460 / 1920), int(alto_pantalla * 30 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.txtContrasenia.setFont(font)
        self.txtContrasenia.setStyleSheet("background-color: white;")
        self.txtContrasenia.setText("")
        self.txtContrasenia.setObjectName("txtContrasenia")
        self.btnIngresar = QtWidgets.QPushButton(self.centralwidget)
        self.btnIngresar.setGeometry(QtCore.QRect(int(ancho_pantalla * 760 / 1920), int(alto_pantalla * 110 / 1080), int(ancho_pantalla * 160 / 1920), int(alto_pantalla * 50 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.btnIngresar.setFont(font)
        valor = int(ancho_pantalla * 25 / 1920)
        self.btnIngresar.setStyleSheet(f"background-color: rgb(255, 0, 0); border-radius: {valor}px;  color: white;")
        self.btnIngresar.setObjectName("btnIngresar")
        self.btnSalir = QtWidgets.QPushButton(self.centralwidget)
        self.btnSalir.setGeometry(QtCore.QRect(int(ancho_pantalla * 760 / 1920), int(alto_pantalla * 210 / 1080), int(ancho_pantalla * 160 / 1920), int(alto_pantalla * 50 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.btnSalir.setFont(font)
        valor = int(ancho_pantalla * 25 / 1920)
        self.btnSalir.setStyleSheet(f"background-color: rgb(255, 0, 0); border-radius: {valor}px;  color: white;")
        self.btnSalir.setObjectName("btnSalir")
        self.btnOlvideContrasenia = QtWidgets.QPushButton(self.centralwidget)
        self.btnOlvideContrasenia.setGeometry(QtCore.QRect(int(ancho_pantalla * 160 / 1920), int(alto_pantalla * 290 / 1080), int(ancho_pantalla * 260 / 1920), int(alto_pantalla * 23 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.btnOlvideContrasenia.setFont(font)
        self.btnOlvideContrasenia.setStyleSheet("color: rgb(180, 180, 255);")
        self.btnOlvideContrasenia.setObjectName("btnOlvideContrasenia")
        self.btnRecuperarPorContrasenia = QtWidgets.QPushButton(self.centralwidget)
        self.btnRecuperarPorContrasenia.setGeometry(QtCore.QRect(int(ancho_pantalla * 50 / 1920), int(alto_pantalla * 380 / 1080), int(ancho_pantalla * 380 / 1920), int(alto_pantalla * 50 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.btnRecuperarPorContrasenia.setFont(font)
        valor = int(ancho_pantalla * 25 / 1920)
        self.btnRecuperarPorContrasenia.setStyleSheet(f"background-color: rgb(255, 0, 0); border-radius: {valor}px;  color: white;")
        self.btnRecuperarPorContrasenia.setObjectName("btnRecuperarPorContrasenia")
        self.btnRecuperarPorPregunta = QtWidgets.QPushButton(self.centralwidget)
        self.btnRecuperarPorPregunta.setGeometry(QtCore.QRect(int(ancho_pantalla * 540 / 1920), int(alto_pantalla * 380 / 1080), int(ancho_pantalla * 380 / 1920), int(alto_pantalla * 50 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.btnRecuperarPorPregunta.setFont(font)
        valor = int(ancho_pantalla * 25 / 1920)
        self.btnRecuperarPorPregunta.setStyleSheet(f"background-color: rgb(255, 0, 0); border-radius: {valor}px;  color: white;")
        self.btnRecuperarPorPregunta.setObjectName("btnRecuperarPorPregunta")
        self.lblContraseniaAnterior = QtWidgets.QLabel(self.centralwidget)
        self.lblContraseniaAnterior.setGeometry(QtCore.QRect(int(ancho_pantalla * 50 / 1920), int(alto_pantalla * 370 / 1080), int(ancho_pantalla * 180 / 1920), int(alto_pantalla * 14 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.lblContraseniaAnterior.setFont(font)
        self.lblContraseniaAnterior.setStyleSheet("color: white;")
        self.lblContraseniaAnterior.setObjectName("lblContraseniaAnterior")
        self.txtContraseniaAnterior = QtWidgets.QLineEdit(self.centralwidget)
        self.txtContraseniaAnterior.setGeometry(QtCore.QRect(int(ancho_pantalla * 50 / 1920), int(alto_pantalla * 400 / 1080), int(ancho_pantalla * 460 / 1920), int(alto_pantalla * 30 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.txtContraseniaAnterior.setFont(font)
        self.txtContraseniaAnterior.setStyleSheet("background-color: white;")
        self.txtContraseniaAnterior.setText("")
        self.txtContraseniaAnterior.setObjectName("txtContraseniaAnterior")
        self.btnAceptarContrasenia = QtWidgets.QPushButton(self.centralwidget)
        self.btnAceptarContrasenia.setGeometry(QtCore.QRect(int(ancho_pantalla * 640 / 1920), int(alto_pantalla * 390 / 1080), int(ancho_pantalla * 130 / 1920), int(alto_pantalla * 50 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.btnAceptarContrasenia.setFont(font)
        valor = int(ancho_pantalla * 25 / 1920)
        self.btnAceptarContrasenia.setStyleSheet(f"background-color: rgb(255, 0, 0); border-radius: {valor}px;  color: white;")
        self.btnAceptarContrasenia.setObjectName("btnAceptarContrasenia")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(int(ancho_pantalla * 0 / 1920), int(alto_pantalla * 330 / 1080), int(ancho_pantalla * 970 / 1920), int(alto_pantalla * 3 / 1080)))
        self.line.setStyleSheet("background-color: white;")
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.btnCancelarContrasenia = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancelarContrasenia.setGeometry(QtCore.QRect(int(ancho_pantalla * 800 / 1920), int(alto_pantalla * 380 / 1080), int(ancho_pantalla * 130 / 1920), int(alto_pantalla * 50 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.btnCancelarContrasenia.setFont(font)
        valor = int(ancho_pantalla * 25 / 1920)
        self.btnCancelarContrasenia.setStyleSheet(f"background-color: rgb(255, 0, 0); border-radius: {valor}px;  color: white;")
        self.btnCancelarContrasenia.setObjectName("btnCancelarContrasenia")
        self.btnAceptarPregunta = QtWidgets.QPushButton(self.centralwidget)
        self.btnAceptarPregunta.setGeometry(QtCore.QRect(int(ancho_pantalla * 640 / 1920), int(alto_pantalla * 390 / 1080), int(ancho_pantalla * 130 / 1920), int(alto_pantalla * 50 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.btnAceptarPregunta.setFont(font)
        valor = int(ancho_pantalla * 25 / 1920)
        self.btnAceptarPregunta.setStyleSheet(f"background-color: rgb(255, 0, 0); border-radius: {valor}px;  color: white;")
        self.btnAceptarPregunta.setObjectName("btnAceptarPregunta")
        self.btnCancelarPregunta = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancelarPregunta.setGeometry(QtCore.QRect(int(ancho_pantalla * 800 / 1920), int(alto_pantalla * 390 / 1080), int(ancho_pantalla * 130 / 1920), int(alto_pantalla * 50 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.btnCancelarPregunta.setFont(font)
        valor = int(ancho_pantalla * 25 / 1920)
        self.btnCancelarPregunta.setStyleSheet(f"background-color: rgb(255, 0, 0); border-radius: {valor}px;  color: white;")
        self.btnCancelarPregunta.setObjectName("btnCancelarPregunta")
        self.txtRespuesta = QtWidgets.QLineEdit(self.centralwidget)
        self.txtRespuesta.setGeometry(QtCore.QRect(int(ancho_pantalla * 50 / 1920), int(alto_pantalla * 410 / 1080), int(ancho_pantalla * 460 / 1920), int(alto_pantalla * 30 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.txtRespuesta.setFont(font)
        self.txtRespuesta.setStyleSheet("background-color: white;")
        self.txtRespuesta.setText("")
        self.txtRespuesta.setObjectName("txtRespuesta")
        self.cbxPreguntas = QtWidgets.QComboBox(self.centralwidget)
        self.cbxPreguntas.setGeometry(QtCore.QRect(int(ancho_pantalla * 50 / 1920), int(alto_pantalla * 360 / 1080), int(ancho_pantalla * 370 / 1920), int(alto_pantalla * 30 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.cbxPreguntas.setFont(font)
        self.cbxPreguntas.setStyleSheet("background-color: white; color: black;")
        self.cbxPreguntas.setObjectName("cbxPreguntas")
        frmAcceso.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmAcceso)
        self.cbxPreguntas.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(frmAcceso)

    def retranslateUi(self, frmAcceso):
        _translate = QtCore.QCoreApplication.translate
        frmAcceso.setWindowTitle(_translate("frmAcceso", "MainWindow"))
        self.label.setText(_translate("frmAcceso", "Acceso al sistema"))
        self.label_2.setText(_translate("frmAcceso", "Usuario"))
        self.label_3.setText(_translate("frmAcceso", "Contraseña"))
        self.btnIngresar.setText(_translate("frmAcceso", "Ingresar"))
        self.btnSalir.setText(_translate("frmAcceso", "Salir"))
        self.btnOlvideContrasenia.setText(_translate("frmAcceso", "No recuerdo mi contraseña"))
        self.btnRecuperarPorContrasenia.setText(_translate("frmAcceso", "Ingresar con contraseña anterior"))
        self.btnRecuperarPorPregunta.setText(_translate("frmAcceso", "Ingresar con pregunta de validación"))
        self.lblContraseniaAnterior.setText(_translate("frmAcceso", "Contraseñaanterior"))
        self.btnAceptarContrasenia.setText(_translate("frmAcceso", "Aceptar"))
        self.btnCancelarContrasenia.setText(_translate("frmAcceso", "Cancelar"))
        self.btnAceptarPregunta.setText(_translate("frmAcceso", "Aceptar"))
        self.btnCancelarPregunta.setText(_translate("frmAcceso", "Cancelar"))
import Iconos_rc
