# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Proyectos\Proyectos_Python\Odontologia\Interfaces\guiCambioContrasenia.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import ctypes


class Ui_frmCambioContrasenia(object):
    def setupUi(self, frmCambioContrasenia):
        #Obtenemos el ancho y alto de la pantalla
        user32 = ctypes.windll.user32
        ancho_pantalla = user32.GetSystemMetrics(0)
        alto_pantalla = user32.GetSystemMetrics(1)
        #
        frmCambioContrasenia.setObjectName("frmCambioContrasenia")
        frmCambioContrasenia.resize(int(ancho_pantalla * 1443 / 1920), int(alto_pantalla * 697 / 1080))
        frmCambioContrasenia.setWindowOpacity(0.0)
        valor = int(ancho_pantalla * 50 / 1920)
        frmCambioContrasenia.setStyleSheet(f"background-color: rgb(40, 0, 70); border-radius: {valor}px; ")
        self.centralwidget = QtWidgets.QWidget(frmCambioContrasenia)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(int(ancho_pantalla * 20 / 1920), int(alto_pantalla * 200 / 1080), int(ancho_pantalla * 80 / 1920), int(alto_pantalla * 20 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.label.setFont(font)
        self.label.setStyleSheet("color: white;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(int(ancho_pantalla * 20 / 1920), int(alto_pantalla * 250 / 1080), int(ancho_pantalla * 80 / 1920), int(alto_pantalla * 20 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: white;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(int(ancho_pantalla * 20 / 1920), int(alto_pantalla * 300 / 1080), int(ancho_pantalla * 80 / 1920), int(alto_pantalla * 20 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: white;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(int(ancho_pantalla * 20 / 1920), int(alto_pantalla * 400 / 1080), int(ancho_pantalla * 170 / 1920), int(alto_pantalla * 20 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: white;")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(int(ancho_pantalla * 20 / 1920), int(alto_pantalla * 450 / 1080), int(ancho_pantalla * 180 / 1920), int(alto_pantalla * 20 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: white;")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(int(ancho_pantalla * 130 / 1920), int(alto_pantalla * 30 / 1080), int(ancho_pantalla * 540 / 1920), int(alto_pantalla * 50 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 40 / 1920))
        font.setItalic(False)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: white;")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(int(ancho_pantalla * 20 / 1920), int(alto_pantalla * 350 / 1080), int(ancho_pantalla * 170 / 1920), int(alto_pantalla * 20 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: white;")
        self.label_7.setObjectName("label_7")
        self.txtNombre = QtWidgets.QLineEdit(self.centralwidget)
        self.txtNombre.setEnabled(False)
        self.txtNombre.setGeometry(QtCore.QRect(int(ancho_pantalla * 200 / 1920), int(alto_pantalla * 190 / 1080), int(ancho_pantalla * 280 / 1920), int(alto_pantalla * 30 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.txtNombre.setFont(font)
        valor = int(ancho_pantalla * 0 / 1920)
        self.txtNombre.setStyleSheet(f"background-color: white; color black; border-radius: {valor}px; ")
        self.txtNombre.setText("")
        self.txtNombre.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.txtNombre.setObjectName("txtNombre")
        self.txtApellido = QtWidgets.QLineEdit(self.centralwidget)
        self.txtApellido.setEnabled(False)
        self.txtApellido.setGeometry(QtCore.QRect(int(ancho_pantalla * 200 / 1920), int(alto_pantalla * 240 / 1080), int(ancho_pantalla * 200 / 1920), int(alto_pantalla * 30 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.txtApellido.setFont(font)
        valor = int(ancho_pantalla * 0 / 1920)
        self.txtApellido.setStyleSheet(f"background-color: white; color black; border-radius: {valor}px; ")
        self.txtApellido.setText("")
        self.txtApellido.setObjectName("txtApellido")
        self.txtContraseniaActual = QtWidgets.QLineEdit(self.centralwidget)
        self.txtContraseniaActual.setGeometry(QtCore.QRect(int(ancho_pantalla * 200 / 1920), int(alto_pantalla * 340 / 1080), int(ancho_pantalla * 380 / 1920), int(alto_pantalla * 30 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.txtContraseniaActual.setFont(font)
        valor = int(ancho_pantalla * 0 / 1920)
        self.txtContraseniaActual.setStyleSheet(f"background-color: white; color black; border-radius: {valor}px; ")
        self.txtContraseniaActual.setText("")
        self.txtContraseniaActual.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtContraseniaActual.setObjectName("txtContraseniaActual")
        self.txtContraseniaNueva = QtWidgets.QLineEdit(self.centralwidget)
        self.txtContraseniaNueva.setGeometry(QtCore.QRect(int(ancho_pantalla * 200 / 1920), int(alto_pantalla * 390 / 1080), int(ancho_pantalla * 380 / 1920), int(alto_pantalla * 30 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.txtContraseniaNueva.setFont(font)
        valor = int(ancho_pantalla * 0 / 1920)
        self.txtContraseniaNueva.setStyleSheet(f"background-color: white; color black; border-radius: {valor}px; ")
        self.txtContraseniaNueva.setText("")
        self.txtContraseniaNueva.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtContraseniaNueva.setObjectName("txtContraseniaNueva")
        self.txtContraseniaRepetir = QtWidgets.QLineEdit(self.centralwidget)
        self.txtContraseniaRepetir.setGeometry(QtCore.QRect(int(ancho_pantalla * 200 / 1920), int(alto_pantalla * 440 / 1080), int(ancho_pantalla * 380 / 1920), int(alto_pantalla * 30 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.txtContraseniaRepetir.setFont(font)
        valor = int(ancho_pantalla * 0 / 1920)
        self.txtContraseniaRepetir.setStyleSheet(f"background-color: white; color black; border-radius: {valor}px; ")
        self.txtContraseniaRepetir.setText("")
        self.txtContraseniaRepetir.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtContraseniaRepetir.setObjectName("txtContraseniaRepetir")
        self.txtUsuario = QtWidgets.QLineEdit(self.centralwidget)
        self.txtUsuario.setEnabled(False)
        self.txtUsuario.setGeometry(QtCore.QRect(int(ancho_pantalla * 200 / 1920), int(alto_pantalla * 290 / 1080), int(ancho_pantalla * 170 / 1920), int(alto_pantalla * 30 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.txtUsuario.setFont(font)
        valor = int(ancho_pantalla * 0 / 1920)
        self.txtUsuario.setStyleSheet(f"background-color: white; color black; border-radius: {valor}px; ")
        self.txtUsuario.setText("")
        self.txtUsuario.setObjectName("txtUsuario")
        self.toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton.setGeometry(QtCore.QRect(int(ancho_pantalla * 550 / 1920), int(alto_pantalla * 530 / 1080), int(ancho_pantalla * 22 / 1920), int(alto_pantalla * 20 / 1080)))
        self.toolButton.setObjectName("toolButton")
        self.btnGuardar = QtWidgets.QPushButton(self.centralwidget)
        self.btnGuardar.setGeometry(QtCore.QRect(int(ancho_pantalla * 30 / 1920), int(alto_pantalla * 610 / 1080), int(ancho_pantalla * 130 / 1920), int(alto_pantalla * 50 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.btnGuardar.setFont(font)
        valor = int(ancho_pantalla * 25 / 1920)
        self.btnGuardar.setStyleSheet(f"background-color: rgb(255, 0, 0); border-radius: {valor}px;  color: white;")
        self.btnGuardar.setObjectName("btnGuardar")
        self.btnBorrar = QtWidgets.QPushButton(self.centralwidget)
        self.btnBorrar.setGeometry(QtCore.QRect(int(ancho_pantalla * 200 / 1920), int(alto_pantalla * 610 / 1080), int(ancho_pantalla * 130 / 1920), int(alto_pantalla * 50 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.btnBorrar.setFont(font)
        valor = int(ancho_pantalla * 25 / 1920)
        self.btnBorrar.setStyleSheet(f"background-color: rgb(255, 0, 0); border-radius: {valor}px;  color: white;")
        self.btnBorrar.setObjectName("btnBorrar")
        self.btnCerrar = QtWidgets.QPushButton(self.centralwidget)
        self.btnCerrar.setGeometry(QtCore.QRect(int(ancho_pantalla * 370 / 1920), int(alto_pantalla * 610 / 1080), int(ancho_pantalla * 130 / 1920), int(alto_pantalla * 50 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.btnCerrar.setFont(font)
        valor = int(ancho_pantalla * 25 / 1920)
        self.btnCerrar.setStyleSheet(f"background-color: rgb(255, 0, 0); border-radius: {valor}px;  color: white;")
        self.btnCerrar.setObjectName("btnCerrar")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(int(ancho_pantalla * 30 / 1920), int(alto_pantalla * 30 / 1080), int(ancho_pantalla * 70 / 1920), int(alto_pantalla * 70 / 1080)))
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Imagenes/Configuracion_usuarios.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(int(ancho_pantalla * 70 / 1920), int(alto_pantalla * 70 / 1080)))
        self.pushButton.setObjectName("pushButton")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(int(ancho_pantalla * 610 / 1920), int(alto_pantalla * 130 / 1080), int(ancho_pantalla * 3 / 1920), int(alto_pantalla * 460 / 1080)))
        self.line.setStyleSheet("background-color: white;")
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(int(ancho_pantalla * 660 / 1920), int(alto_pantalla * 120 / 1080), int(ancho_pantalla * 540 / 1920), int(alto_pantalla * 50 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 25 / 1920))
        font.setItalic(False)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: white;")
        self.label_8.setObjectName("label_8")
        self.chkMusica = QtWidgets.QCheckBox(self.centralwidget)
        self.chkMusica.setGeometry(QtCore.QRect(int(ancho_pantalla * 652 / 1920), int(alto_pantalla * 180 / 1080), int(ancho_pantalla * 350 / 1920), int(alto_pantalla * 18 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.chkMusica.setFont(font)
        self.chkMusica.setStyleSheet("color:white;")
        self.chkMusica.setObjectName("chkMusica")
        self.txtMusica = QtWidgets.QLineEdit(self.centralwidget)
        self.txtMusica.setGeometry(QtCore.QRect(int(ancho_pantalla * 652 / 1920), int(alto_pantalla * 210 / 1080), int(ancho_pantalla * 340 / 1920), int(alto_pantalla * 30 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.txtMusica.setFont(font)
        valor = int(ancho_pantalla * 0 / 1920)
        self.txtMusica.setStyleSheet(f"background-color: white; color black; border-radius: {valor}px; ")
        self.txtMusica.setText("")
        self.txtMusica.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtMusica.setObjectName("txtMusica")
        self.chkComida = QtWidgets.QCheckBox(self.centralwidget)
        self.chkComida.setGeometry(QtCore.QRect(int(ancho_pantalla * 652 / 1920), int(alto_pantalla * 270 / 1080), int(ancho_pantalla * 180 / 1920), int(alto_pantalla * 18 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.chkComida.setFont(font)
        self.chkComida.setStyleSheet("color:white;")
        self.chkComida.setObjectName("chkComida")
        self.txtComida = QtWidgets.QLineEdit(self.centralwidget)
        self.txtComida.setGeometry(QtCore.QRect(int(ancho_pantalla * 652 / 1920), int(alto_pantalla * 300 / 1080), int(ancho_pantalla * 340 / 1920), int(alto_pantalla * 30 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.txtComida.setFont(font)
        valor = int(ancho_pantalla * 0 / 1920)
        self.txtComida.setStyleSheet(f"background-color: white; color black; border-radius: {valor}px; ")
        self.txtComida.setText("")
        self.txtComida.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtComida.setObjectName("txtComida")
        self.chkNumero = QtWidgets.QCheckBox(self.centralwidget)
        self.chkNumero.setGeometry(QtCore.QRect(int(ancho_pantalla * 652 / 1920), int(alto_pantalla * 360 / 1080), int(ancho_pantalla * 180 / 1920), int(alto_pantalla * 18 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.chkNumero.setFont(font)
        self.chkNumero.setStyleSheet("color:white;")
        self.chkNumero.setObjectName("chkNumero")
        self.txtNumero = QtWidgets.QLineEdit(self.centralwidget)
        self.txtNumero.setGeometry(QtCore.QRect(int(ancho_pantalla * 650 / 1920), int(alto_pantalla * 390 / 1080), int(ancho_pantalla * 340 / 1920), int(alto_pantalla * 30 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.txtNumero.setFont(font)
        valor = int(ancho_pantalla * 0 / 1920)
        self.txtNumero.setStyleSheet(f"background-color: white; color black; border-radius: {valor}px; ")
        self.txtNumero.setText("")
        self.txtNumero.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtNumero.setObjectName("txtNumero")
        self.chkAnimal = QtWidgets.QCheckBox(self.centralwidget)
        self.chkAnimal.setGeometry(QtCore.QRect(int(ancho_pantalla * 650 / 1920), int(alto_pantalla * 450 / 1080), int(ancho_pantalla * 180 / 1920), int(alto_pantalla * 18 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.chkAnimal.setFont(font)
        self.chkAnimal.setStyleSheet("color:white;")
        self.chkAnimal.setObjectName("chkAnimal")
        self.txtAnimal = QtWidgets.QLineEdit(self.centralwidget)
        self.txtAnimal.setGeometry(QtCore.QRect(int(ancho_pantalla * 650 / 1920), int(alto_pantalla * 480 / 1080), int(ancho_pantalla * 340 / 1920), int(alto_pantalla * 30 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.txtAnimal.setFont(font)
        valor = int(ancho_pantalla * 0 / 1920)
        self.txtAnimal.setStyleSheet(f"background-color: white; color black; border-radius: {valor}px; ")
        self.txtAnimal.setText("")
        self.txtAnimal.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtAnimal.setObjectName("txtAnimal")
        self.chkPelicula = QtWidgets.QCheckBox(self.centralwidget)
        self.chkPelicula.setGeometry(QtCore.QRect(int(ancho_pantalla * 650 / 1920), int(alto_pantalla * 530 / 1080), int(ancho_pantalla * 290 / 1920), int(alto_pantalla * 18 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.chkPelicula.setFont(font)
        self.chkPelicula.setStyleSheet("color:white;")
        self.chkPelicula.setObjectName("chkPelicula")
        self.txtPelicula = QtWidgets.QLineEdit(self.centralwidget)
        self.txtPelicula.setGeometry(QtCore.QRect(int(ancho_pantalla * 650 / 1920), int(alto_pantalla * 560 / 1080), int(ancho_pantalla * 340 / 1920), int(alto_pantalla * 30 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.txtPelicula.setFont(font)
        valor = int(ancho_pantalla * 0 / 1920)
        self.txtPelicula.setStyleSheet(f"background-color: white; color black; border-radius: {valor}px; ")
        self.txtPelicula.setText("")
        self.txtPelicula.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtPelicula.setObjectName("txtPelicula")
        self.chkLibro = QtWidgets.QCheckBox(self.centralwidget)
        self.chkLibro.setGeometry(QtCore.QRect(int(ancho_pantalla * 1060 / 1920), int(alto_pantalla * 180 / 1080), int(ancho_pantalla * 240 / 1920), int(alto_pantalla * 18 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.chkLibro.setFont(font)
        self.chkLibro.setStyleSheet("color:white;")
        self.chkLibro.setObjectName("chkLibro")
        self.txtLibro = QtWidgets.QLineEdit(self.centralwidget)
        self.txtLibro.setGeometry(QtCore.QRect(int(ancho_pantalla * 1060 / 1920), int(alto_pantalla * 210 / 1080), int(ancho_pantalla * 340 / 1920), int(alto_pantalla * 30 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.txtLibro.setFont(font)
        valor = int(ancho_pantalla * 0 / 1920)
        self.txtLibro.setStyleSheet(f"background-color: white; color black; border-radius: {valor}px; ")
        self.txtLibro.setText("")
        self.txtLibro.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtLibro.setObjectName("txtLibro")
        self.chkLugarNacimiento = QtWidgets.QCheckBox(self.centralwidget)
        self.chkLugarNacimiento.setGeometry(QtCore.QRect(int(ancho_pantalla * 1060 / 1920), int(alto_pantalla * 270 / 1080), int(ancho_pantalla * 240 / 1920), int(alto_pantalla * 18 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.chkLugarNacimiento.setFont(font)
        self.chkLugarNacimiento.setStyleSheet("color:white;")
        self.chkLugarNacimiento.setObjectName("chkLugarNacimiento")
        self.txtLugarNacimiento = QtWidgets.QLineEdit(self.centralwidget)
        self.txtLugarNacimiento.setGeometry(QtCore.QRect(int(ancho_pantalla * 1060 / 1920), int(alto_pantalla * 300 / 1080), int(ancho_pantalla * 340 / 1920), int(alto_pantalla * 30 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.txtLugarNacimiento.setFont(font)
        valor = int(ancho_pantalla * 0 / 1920)
        self.txtLugarNacimiento.setStyleSheet(f"background-color: white; color black; border-radius: {valor}px; ")
        self.txtLugarNacimiento.setText("")
        self.txtLugarNacimiento.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtLugarNacimiento.setObjectName("txtLugarNacimiento")
        self.chkEscuela = QtWidgets.QCheckBox(self.centralwidget)
        self.chkEscuela.setGeometry(QtCore.QRect(int(ancho_pantalla * 1060 / 1920), int(alto_pantalla * 360 / 1080), int(ancho_pantalla * 240 / 1920), int(alto_pantalla * 18 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.chkEscuela.setFont(font)
        self.chkEscuela.setStyleSheet("color:white;")
        self.chkEscuela.setObjectName("chkEscuela")
        self.txtEscuela = QtWidgets.QLineEdit(self.centralwidget)
        self.txtEscuela.setGeometry(QtCore.QRect(int(ancho_pantalla * 1060 / 1920), int(alto_pantalla * 390 / 1080), int(ancho_pantalla * 340 / 1920), int(alto_pantalla * 30 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.txtEscuela.setFont(font)
        valor = int(ancho_pantalla * 0 / 1920)
        self.txtEscuela.setStyleSheet(f"background-color: white; color black; border-radius: {valor}px; ")
        self.txtEscuela.setText("")
        self.txtEscuela.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtEscuela.setObjectName("txtEscuela")
        self.chkMascota = QtWidgets.QCheckBox(self.centralwidget)
        self.chkMascota.setGeometry(QtCore.QRect(int(ancho_pantalla * 1060 / 1920), int(alto_pantalla * 460 / 1080), int(ancho_pantalla * 240 / 1920), int(alto_pantalla * 18 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.chkMascota.setFont(font)
        self.chkMascota.setStyleSheet("color:white;")
        self.chkMascota.setObjectName("chkMascota")
        self.txtMascota = QtWidgets.QLineEdit(self.centralwidget)
        self.txtMascota.setGeometry(QtCore.QRect(int(ancho_pantalla * 1060 / 1920), int(alto_pantalla * 490 / 1080), int(ancho_pantalla * 340 / 1920), int(alto_pantalla * 30 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.txtMascota.setFont(font)
        valor = int(ancho_pantalla * 0 / 1920)
        self.txtMascota.setStyleSheet(f"background-color: white; color black; border-radius: {valor}px; ")
        self.txtMascota.setText("")
        self.txtMascota.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtMascota.setObjectName("txtMascota")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(int(ancho_pantalla * 1100 / 1920), int(alto_pantalla * 580 / 1080), int(ancho_pantalla * 260 / 1920), int(alto_pantalla * 30 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 12 / 1920))
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color:white;")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        frmCambioContrasenia.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmCambioContrasenia)
        QtCore.QMetaObject.connectSlotsByName(frmCambioContrasenia)

    def retranslateUi(self, frmCambioContrasenia):
        _translate = QtCore.QCoreApplication.translate
        frmCambioContrasenia.setWindowTitle(_translate("frmCambioContrasenia", "MainWindow"))
        self.label.setText(_translate("frmCambioContrasenia", "Nombre"))
        self.label_2.setText(_translate("frmCambioContrasenia", "Apellido"))
        self.label_3.setText(_translate("frmCambioContrasenia", "Usuario"))
        self.label_4.setText(_translate("frmCambioContrasenia", "Contraseña nueva"))
        self.label_5.setText(_translate("frmCambioContrasenia", "Repetir contraseña"))
        self.label_6.setText(_translate("frmCambioContrasenia", "Cambio de contraseña"))
        self.label_7.setText(_translate("frmCambioContrasenia", "Contraseña actual"))
        self.toolButton.setText(_translate("frmCambioContrasenia", "..."))
        self.btnGuardar.setText(_translate("frmCambioContrasenia", "Guardar"))
        self.btnBorrar.setText(_translate("frmCambioContrasenia", "Borrar"))
        self.btnCerrar.setText(_translate("frmCambioContrasenia", "Cerrar"))
        self.label_8.setText(_translate("frmCambioContrasenia", "Preguntas de validación"))
        self.chkMusica.setText(_translate("frmCambioContrasenia", "Cantante o grupo de música favorito"))
        self.chkComida.setText(_translate("frmCambioContrasenia", "Comida favorita"))
        self.chkNumero.setText(_translate("frmCambioContrasenia", "Número favorito"))
        self.chkAnimal.setText(_translate("frmCambioContrasenia", "Animal favorito"))
        self.chkPelicula.setText(_translate("frmCambioContrasenia", "Película favorita"))
        self.chkLibro.setText(_translate("frmCambioContrasenia", "Libro favorito"))
        self.chkLugarNacimiento.setText(_translate("frmCambioContrasenia", "Lugar de nacimiento"))
        self.chkEscuela.setText(_translate("frmCambioContrasenia", "Escuela donde estudió"))
        self.chkMascota.setText(_translate("frmCambioContrasenia", "Nombre de la mascota"))
        self.label_9.setText(_translate("frmCambioContrasenia", "Seleccione 3 opciones y escriba la respuesta correspondiente"))
import Iconos_rc
