# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Proyectos\Proyectos_Python\Odontologia\Interfaces\guiPrincipal.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import ctypes


class Ui_frmPrincipal(object):
    def setupUi(self, frmPrincipal):
        #Obtenemos el ancho y alto de la pantalla
        user32 = ctypes.windll.user32
        ancho_pantalla = user32.GetSystemMetrics(0)
        alto_pantalla = user32.GetSystemMetrics(1)
        #
        frmPrincipal.setObjectName("frmPrincipal")
        frmPrincipal.resize(int(ancho_pantalla * 1920 / 1920), int(alto_pantalla * 1045 / 1080))
        self.centralwidget = QtWidgets.QWidget(frmPrincipal)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(int(ancho_pantalla * 270 / 1920), int(alto_pantalla * 190 / 1080), int(ancho_pantalla * 770 / 1920), int(alto_pantalla * 40 / 1080)))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(int(ancho_pantalla * 30 / 1920))
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(int(ancho_pantalla * 340 / 1920), int(alto_pantalla * 100 / 1080), int(ancho_pantalla * 670 / 1920), int(alto_pantalla * 60 / 1080)))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(int(ancho_pantalla * 50 / 1920))
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lblFecha = QtWidgets.QLabel(self.centralwidget)
        self.lblFecha.setGeometry(QtCore.QRect(int(ancho_pantalla * 230 / 1920), int(alto_pantalla * 1030 / 1080), int(ancho_pantalla * 100 / 1920), int(alto_pantalla * 30 / 1080)))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblFecha.sizePolicy().hasHeightForWidth())
        self.lblFecha.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 20 / 1920))
        self.lblFecha.setFont(font)
        self.lblFecha.setObjectName("lblFecha")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(int(ancho_pantalla * 0 / 1920), int(alto_pantalla * 1000 / 1080), int(ancho_pantalla * 1920 / 1920), int(alto_pantalla * 4 / 1080)))
        self.line.setStyleSheet("")
        self.line.setLineWidth(5)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.lcdHora = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdHora.setGeometry(QtCore.QRect(int(ancho_pantalla * 30 / 1920), int(alto_pantalla * 1010 / 1080), int(ancho_pantalla * 180 / 1920), int(alto_pantalla * 60 / 1080)))
        self.lcdHora.setDigitCount(8)
        self.lcdHora.setObjectName("lcdHora")
        self.btnCerrar = QtWidgets.QPushButton(self.centralwidget)
        self.btnCerrar.setGeometry(QtCore.QRect(int(ancho_pantalla * 1830 / 1920), int(alto_pantalla * 40 / 1080), int(ancho_pantalla * 50 / 1920), int(alto_pantalla * 50 / 1080)))
        self.btnCerrar.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.btnCerrar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Imagenes/Cerrar.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btnCerrar.setIcon(icon)
        self.btnCerrar.setIconSize(QtCore.QSize(int(ancho_pantalla * 50 / 1920), int(alto_pantalla * 50 / 1080)))
        self.btnCerrar.setObjectName("btnCerrar")
        self.btnMinimizar = QtWidgets.QPushButton(self.centralwidget)
        self.btnMinimizar.setGeometry(QtCore.QRect(int(ancho_pantalla * 1770 / 1920), int(alto_pantalla * 40 / 1080), int(ancho_pantalla * 50 / 1920), int(alto_pantalla * 50 / 1080)))
        self.btnMinimizar.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.btnMinimizar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Imagenes/Minimizar.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btnMinimizar.setIcon(icon1)
        self.btnMinimizar.setIconSize(QtCore.QSize(int(ancho_pantalla * 50 / 1920), int(alto_pantalla * 50 / 1080)))
        self.btnMinimizar.setObjectName("btnMinimizar")
        self.btnUsuarios = QtWidgets.QPushButton(self.centralwidget)
        self.btnUsuarios.setGeometry(QtCore.QRect(int(ancho_pantalla * 30 / 1920), int(alto_pantalla * 740 / 1080), int(ancho_pantalla * 70 / 1920), int(alto_pantalla * 70 / 1080)))
        valor = int(ancho_pantalla * 35 / 1920)
        self.btnUsuarios.setStyleSheet(f"background-color: rgba(0, 0, 0, 0); border-radius: {valor}px; ")
        self.btnUsuarios.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Imagenes/UsuariosCeleste_FondoNegro.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btnUsuarios.setIcon(icon2)
        self.btnUsuarios.setIconSize(QtCore.QSize(int(ancho_pantalla * 70 / 1920), int(alto_pantalla * 70 / 1080)))
        self.btnUsuarios.setObjectName("btnUsuarios")
        self.btnSalir = QtWidgets.QPushButton(self.centralwidget)
        self.btnSalir.setGeometry(QtCore.QRect(int(ancho_pantalla * 30 / 1920), int(alto_pantalla * 920 / 1080), int(ancho_pantalla * 70 / 1920), int(alto_pantalla * 70 / 1080)))
        valor = int(ancho_pantalla * 35 / 1920)
        self.btnSalir.setStyleSheet(f"background-color: rgba(0, 0, 0, 0); border-radius: {valor}px; ")
        self.btnSalir.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Imagenes/FlechaCeleste_BaseNegra.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btnSalir.setIcon(icon3)
        self.btnSalir.setIconSize(QtCore.QSize(int(ancho_pantalla * 70 / 1920), int(alto_pantalla * 70 / 1080)))
        self.btnSalir.setObjectName("btnSalir")
        self.btnPacientes = QtWidgets.QPushButton(self.centralwidget)
        self.btnPacientes.setGeometry(QtCore.QRect(int(ancho_pantalla * 30 / 1920), int(alto_pantalla * 470 / 1080), int(ancho_pantalla * 70 / 1920), int(alto_pantalla * 70 / 1080)))
        valor = int(ancho_pantalla * 35 / 1920)
        self.btnPacientes.setStyleSheet(f"background-color: rgba(0, 0, 0, 0); border-radius: {valor}px; ")
        self.btnPacientes.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Imagenes/PacienteCeleste_BaseNegra.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btnPacientes.setIcon(icon4)
        self.btnPacientes.setIconSize(QtCore.QSize(int(ancho_pantalla * 70 / 1920), int(alto_pantalla * 70 / 1080)))
        self.btnPacientes.setObjectName("btnPacientes")
        self.btnNosotros = QtWidgets.QPushButton(self.centralwidget)
        self.btnNosotros.setGeometry(QtCore.QRect(int(ancho_pantalla * 30 / 1920), int(alto_pantalla * 830 / 1080), int(ancho_pantalla * 70 / 1920), int(alto_pantalla * 70 / 1080)))
        valor = int(ancho_pantalla * 35 / 1920)
        self.btnNosotros.setStyleSheet(f"background-color: rgba(0, 0, 0, 0); border-radius: {valor}px; ")
        self.btnNosotros.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Imagenes/NosotrosCeleste_BaseNegra.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btnNosotros.setIcon(icon5)
        self.btnNosotros.setIconSize(QtCore.QSize(int(ancho_pantalla * 70 / 1920), int(alto_pantalla * 70 / 1080)))
        self.btnNosotros.setObjectName("btnNosotros")
        self.btnInformes = QtWidgets.QPushButton(self.centralwidget)
        self.btnInformes.setGeometry(QtCore.QRect(int(ancho_pantalla * 30 / 1920), int(alto_pantalla * 560 / 1080), int(ancho_pantalla * 70 / 1920), int(alto_pantalla * 70 / 1080)))
        valor = int(ancho_pantalla * 35 / 1920)
        self.btnInformes.setStyleSheet(f"background-color: rgba(0, 0, 0, 0); border-radius: {valor}px; ")
        self.btnInformes.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Imagenes/InformeCeleste_BaseNegra.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btnInformes.setIcon(icon6)
        self.btnInformes.setIconSize(QtCore.QSize(int(ancho_pantalla * 70 / 1920), int(alto_pantalla * 70 / 1080)))
        self.btnInformes.setObjectName("btnInformes")
        self.btnNotas = QtWidgets.QPushButton(self.centralwidget)
        self.btnNotas.setGeometry(QtCore.QRect(int(ancho_pantalla * 30 / 1920), int(alto_pantalla * 650 / 1080), int(ancho_pantalla * 70 / 1920), int(alto_pantalla * 70 / 1080)))
        valor = int(ancho_pantalla * 35 / 1920)
        self.btnNotas.setStyleSheet(f"background-color: rgba(0, 0, 0, 0); border-radius: {valor}px; ")
        self.btnNotas.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Imagenes/PergaminoCeleste_FondoNegro.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btnNotas.setIcon(icon7)
        self.btnNotas.setIconSize(QtCore.QSize(int(ancho_pantalla * 70 / 1920), int(alto_pantalla * 70 / 1080)))
        self.btnNotas.setObjectName("btnNotas")
        self.btnLogo = QtWidgets.QPushButton(self.centralwidget)
        self.btnLogo.setGeometry(QtCore.QRect(int(ancho_pantalla * 60 / 1920), int(alto_pantalla * 40 / 1080), int(ancho_pantalla * 200 / 1920), int(alto_pantalla * 200 / 1080)))
        self.btnLogo.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.btnLogo.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Imagenes/Logo_odontologia.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btnLogo.setIcon(icon8)
        self.btnLogo.setIconSize(QtCore.QSize(int(ancho_pantalla * 200 / 1920), int(alto_pantalla * 200 / 1080)))
        self.btnLogo.setObjectName("btnLogo")
        self.btnUsuariosDesplegable = QtWidgets.QPushButton(self.centralwidget)
        self.btnUsuariosDesplegable.setGeometry(QtCore.QRect(int(ancho_pantalla * 30 / 1920), int(alto_pantalla * 750 / 1080), int(ancho_pantalla * 70 / 1920), int(alto_pantalla * 50 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.btnUsuariosDesplegable.setFont(font)
        self.btnUsuariosDesplegable.setLayoutDirection(QtCore.Qt.LeftToRight)
        valor = int(ancho_pantalla * 25 / 1920)
        self.btnUsuariosDesplegable.setStyleSheet(f"background-color: rgb(70, 70, 120); color: white; border-radius: {valor}px; ")
        self.btnUsuariosDesplegable.setObjectName("btnUsuariosDesplegable")
        self.btnSalirDesplegable = QtWidgets.QPushButton(self.centralwidget)
        self.btnSalirDesplegable.setGeometry(QtCore.QRect(int(ancho_pantalla * 30 / 1920), int(alto_pantalla * 930 / 1080), int(ancho_pantalla * 70 / 1920), int(alto_pantalla * 50 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.btnSalirDesplegable.setFont(font)
        self.btnSalirDesplegable.setLayoutDirection(QtCore.Qt.LeftToRight)
        valor = int(ancho_pantalla * 25 / 1920)
        self.btnSalirDesplegable.setStyleSheet(f"background-color: rgb(70, 70, 120); color: white; border-radius: {valor}px; ")
        self.btnSalirDesplegable.setObjectName("btnSalirDesplegable")
        self.btnPacientesDesplegable = QtWidgets.QPushButton(self.centralwidget)
        self.btnPacientesDesplegable.setGeometry(QtCore.QRect(int(ancho_pantalla * 30 / 1920), int(alto_pantalla * 480 / 1080), int(ancho_pantalla * 70 / 1920), int(alto_pantalla * 50 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.btnPacientesDesplegable.setFont(font)
        self.btnPacientesDesplegable.setLayoutDirection(QtCore.Qt.LeftToRight)
        valor = int(ancho_pantalla * 25 / 1920)
        self.btnPacientesDesplegable.setStyleSheet(f"background-color: rgb(70, 70, 120); color: white; border-radius: {valor}px; ")
        self.btnPacientesDesplegable.setObjectName("btnPacientesDesplegable")
        self.btnInformesDesplegable = QtWidgets.QPushButton(self.centralwidget)
        self.btnInformesDesplegable.setGeometry(QtCore.QRect(int(ancho_pantalla * 30 / 1920), int(alto_pantalla * 570 / 1080), int(ancho_pantalla * 70 / 1920), int(alto_pantalla * 50 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.btnInformesDesplegable.setFont(font)
        self.btnInformesDesplegable.setLayoutDirection(QtCore.Qt.LeftToRight)
        valor = int(ancho_pantalla * 25 / 1920)
        self.btnInformesDesplegable.setStyleSheet(f"background-color: rgb(70, 70, 120); color: white; border-radius: {valor}px; ")
        self.btnInformesDesplegable.setObjectName("btnInformesDesplegable")
        self.btnNotasDesplegable = QtWidgets.QPushButton(self.centralwidget)
        self.btnNotasDesplegable.setGeometry(QtCore.QRect(int(ancho_pantalla * 30 / 1920), int(alto_pantalla * 660 / 1080), int(ancho_pantalla * 70 / 1920), int(alto_pantalla * 50 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.btnNotasDesplegable.setFont(font)
        self.btnNotasDesplegable.setLayoutDirection(QtCore.Qt.LeftToRight)
        valor = int(ancho_pantalla * 25 / 1920)
        self.btnNotasDesplegable.setStyleSheet(f"background-color: rgb(70, 70, 120); color: white; border-radius: {valor}px; ")
        self.btnNotasDesplegable.setObjectName("btnNotasDesplegable")
        self.btnNosotrosDesplegable = QtWidgets.QPushButton(self.centralwidget)
        self.btnNosotrosDesplegable.setGeometry(QtCore.QRect(int(ancho_pantalla * 30 / 1920), int(alto_pantalla * 840 / 1080), int(ancho_pantalla * 70 / 1920), int(alto_pantalla * 50 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.btnNosotrosDesplegable.setFont(font)
        self.btnNosotrosDesplegable.setLayoutDirection(QtCore.Qt.LeftToRight)
        valor = int(ancho_pantalla * 25 / 1920)
        self.btnNosotrosDesplegable.setStyleSheet(f"background-color: rgb(70, 70, 120); color: white; border-radius: {valor}px; ")
        self.btnNosotrosDesplegable.setObjectName("btnNosotrosDesplegable")
        self.btnLogoEmpresa = QtWidgets.QPushButton(self.centralwidget)
        self.btnLogoEmpresa.setGeometry(QtCore.QRect(int(ancho_pantalla * 1720 / 1920), int(alto_pantalla * 1010 / 1080), int(ancho_pantalla * 180 / 1920), int(alto_pantalla * 60 / 1080)))
        self.btnLogoEmpresa.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.btnLogoEmpresa.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/Imagenes/LHlogo_Lobster_rojoygris.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btnLogoEmpresa.setIcon(icon9)
        self.btnLogoEmpresa.setIconSize(QtCore.QSize(int(ancho_pantalla * 180 / 1920), int(alto_pantalla * 60 / 1080)))
        self.btnLogoEmpresa.setObjectName("btnLogoEmpresa")
        self.btnGestionPacientes = QtWidgets.QPushButton(self.centralwidget)
        self.btnGestionPacientes.setGeometry(QtCore.QRect(int(ancho_pantalla * 110 / 1920), int(alto_pantalla * 340 / 1080), int(ancho_pantalla * 200 / 1920), int(alto_pantalla * 40 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.btnGestionPacientes.setFont(font)
        self.btnGestionPacientes.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.btnGestionPacientes.setObjectName("btnGestionPacientes")
        self.btnAtencionPacientes = QtWidgets.QPushButton(self.centralwidget)
        self.btnAtencionPacientes.setGeometry(QtCore.QRect(int(ancho_pantalla * 110 / 1920), int(alto_pantalla * 300 / 1080), int(ancho_pantalla * 200 / 1920), int(alto_pantalla * 40 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.btnAtencionPacientes.setFont(font)
        self.btnAtencionPacientes.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.btnAtencionPacientes.setObjectName("btnAtencionPacientes")
        self.btnInformesCobros = QtWidgets.QPushButton(self.centralwidget)
        self.btnInformesCobros.setGeometry(QtCore.QRect(int(ancho_pantalla * 110 / 1920), int(alto_pantalla * 450 / 1080), int(ancho_pantalla * 200 / 1920), int(alto_pantalla * 40 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.btnInformesCobros.setFont(font)
        self.btnInformesCobros.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.btnInformesCobros.setObjectName("btnInformesCobros")
        self.btnInformesPagos = QtWidgets.QPushButton(self.centralwidget)
        self.btnInformesPagos.setGeometry(QtCore.QRect(int(ancho_pantalla * 110 / 1920), int(alto_pantalla * 410 / 1080), int(ancho_pantalla * 200 / 1920), int(alto_pantalla * 40 / 1080)))
        font = QtGui.QFont()
        font.setPointSize(int(ancho_pantalla * 15 / 1920))
        self.btnInformesPagos.setFont(font)
        self.btnInformesPagos.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.btnInformesPagos.setObjectName("btnInformesPagos")
        self.btnInformesCobros.raise_()
        self.btnInformesPagos.raise_()
        self.btnGestionPacientes.raise_()
        self.btnAtencionPacientes.raise_()
        self.btnNosotrosDesplegable.raise_()
        self.btnNotasDesplegable.raise_()
        self.btnInformesDesplegable.raise_()
        self.btnPacientesDesplegable.raise_()
        self.btnSalirDesplegable.raise_()
        self.btnUsuariosDesplegable.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.lblFecha.raise_()
        self.line.raise_()
        self.lcdHora.raise_()
        self.btnCerrar.raise_()
        self.btnMinimizar.raise_()
        self.btnUsuarios.raise_()
        self.btnSalir.raise_()
        self.btnPacientes.raise_()
        self.btnNosotros.raise_()
        self.btnInformes.raise_()
        self.btnNotas.raise_()
        self.btnLogo.raise_()
        self.btnLogoEmpresa.raise_()
        frmPrincipal.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmPrincipal)
        QtCore.QMetaObject.connectSlotsByName(frmPrincipal)

    def retranslateUi(self, frmPrincipal):
        _translate = QtCore.QCoreApplication.translate
        frmPrincipal.setWindowTitle(_translate("frmPrincipal", "MainWindow"))
        self.label.setText(_translate("frmPrincipal", "SISTEMA INTEGRAL DE ODONTOLOGÍA"))
        self.label_2.setText(_translate("frmPrincipal", "Dra. Carolina Romero"))
        self.lblFecha.setText(_translate("frmPrincipal", "Hoy es miércoles 12 de diciembre de 2033"))
        self.btnUsuariosDesplegable.setText(_translate("frmPrincipal", "Usuarios"))
        self.btnSalirDesplegable.setText(_translate("frmPrincipal", "Salir"))
        self.btnPacientesDesplegable.setText(_translate("frmPrincipal", "Pacientes"))
        self.btnInformesDesplegable.setText(_translate("frmPrincipal", "Informes"))
        self.btnNotasDesplegable.setText(_translate("frmPrincipal", "Notas"))
        self.btnNosotrosDesplegable.setText(_translate("frmPrincipal", "Nosotros"))
        self.btnGestionPacientes.setText(_translate("frmPrincipal", "Gestión"))
        self.btnAtencionPacientes.setText(_translate("frmPrincipal", "Atención"))
        self.btnInformesCobros.setText(_translate("frmPrincipal", "Cobros"))
        self.btnInformesPagos.setText(_translate("frmPrincipal", "Pagos"))
import Iconos_rc
